# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        MainWindow.setMaximumSize(QtCore.QSize(900, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 900, 500))
        self.label.setMaximumSize(QtCore.QSize(900, 500))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img.png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 360, 152, 51))
        font = QtGui.QFont()
        font.setFamily("Roobert")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"  appearance: none;\n"
"  background-color: #fff;\n"
"  border: 2px solid #1A1A1A;\n"
"  border-radius: 15px;\n"
"  box-sizing: border-box;\n"
"  color: #3B3B3B;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: Roobert,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Helvetica,Arial,sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\";\n"
"  font-size: 16px;\n"
"  font-weight: 600;\n"
"  line-height: normal;\n"
"  margin: 0;\n"
"  min-height:10px;\n"
"  min-width: 0;\n"
"  outline: none;\n"
"  padding: 16px 24px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: all 300ms cubic-bezier(.23, 1, 0.32, 1);\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: 100%;\n"
"  will-change: transform;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"  pointer-events: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  color: #fff;\n"
"  background-color: #1A1A1A;\n"
"  box-shadow: rgba(0, 0, 0, 0.25) 0 8px 15px;\n"
"  transform: translateY(-2px);\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  box-shadow: none;\n"
"  transform: translateY(0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_num = QtWidgets.QLabel(self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(170, 110, 100, 200))
        self.label_num.setMaximumSize(QtCore.QSize(100, 200))
        self.label_num.setText("")
        self.label_num.setPixmap(QtGui.QPixmap("00.png"))
        self.label_num.setObjectName("label_num")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 20, 16, 16))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(138, 12, 19);\n"
"border-radius:2px;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 20, 16, 16))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-radius:2px;\n"
"background-color: rgb(227, 205, 35);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(MainWindow.showMinimized)
        self.pushButton_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Click Me ! "))
        self.label_2.setText(_translate("MainWindow", "Arezaie2002"))



